FROM python:3.10-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/
RUN pip config set global.timeout 300 \
    && pip install --no-cache-dir -r requirements.txt -i https://pypi.org/simple


COPY . /app

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.nodes.run_node"]

